language: python
version:
    - 2.7
notifications:
    email:
        on_success: always
        on_failure: always
before_install: 
    - sudo apt-get install spim
script: 
    - python ./travis/spim-grader.py        # Run the grader
    # - bash ./travis/update.sh             # Push the results to repo
    - python ./travis/spim-grader.py -g     # Fail the build if cases don't pass
